# This is a basic workflow that is manually triggered
name: Run tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: difi/vefa-validator
      options: -v $(pwd):/src

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: ls -la /github/home
    # Runs a single command using the runners shell
    - name: Test CII
      run: build -x -t -p cii /src
      
