name: Run tests

on:
  push:
    branches:
      - master

jobs:
#  run-tests:
#    runs-on: ubuntu-latest
#    container:
#      image: difi/vefa-validator
#      options: -v /home/runner/work/_actions:/src
#    steps:
#    - name: Test CII 1
#      run: build -x -t -p cii /src
#    - name: Test CII 2
#      run: docker run --rm --pull -it difi/vefa-validator build -x -t -p cii /src
#    - name: Test CII
#      run: docker run --rm --pull -it -v /home/runner/work/_actions:/src difi/vefa-validator build -x -t -p cii /src

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check container
        uses: docker://difi/vefa-validator:latest
        with:
          args: build -x -t -p cii /src
