name: Run tests

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: difi/vefa-validator
      options: -v /home/runner/work/_actions:/src
    steps:
    - name: Test CII
      run: docker run --rm --pull -it -v /home/runner/work/_actions:/src difi/vefa-validator build -x -t -p cii /src
